update

diff --git a/hyprutils/hyprutils.SlackBuild b/hyprutils/hyprutils.SlackBuild
--- a/hyprutils/hyprutils.SlackBuild
+++ b/hyprutils/hyprutils.SlackBuild
@@ -21,23 +21,34 @@ Packager="Anagnostakis Ioannis (rizitis@gmail.com) GR"
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
    cd $(dirname "$0") ; CWD=$(pwd)
+# Setup build log file
+LOGFILE="$CWD/build.log"
+exec > >(tee -a "$LOGFILE") 2>&1
+
+echo "Starting build process..."
+start_time=$(date +%s)
+
 
 ##########################-slackdesc-########################################
 # If you have slackdesc installed you need these, else ignore them and comment them.
 # https://slack-desc.sourceforge.net/
 # example of use:
    mkdesc="$(which slackdesc)" || true
-   Homepage="https://github.com/hyprwm/hyprutils"
+   Homepage="Homepage: https://github.com/hyprwm/hyprutils"
+            #|--------------------------------------|#
    SortDesc="Hyprland utilities library"
    LongDesc="Hyprutils is a small C++ library for utilities used across the Hypr* ecosystem.Hyprutils depends on the ABI stability of the stdlib implementation of your compiler. Sover bumps will be done only for hyprutils ABI breaks, not stdlib."
 #############################################################################
+# EDIT FOLLOWING AS NEEDED:
    SRCURL="https://github.com/hyprwm/hyprutils.git"
+   # IF you need:git checkout, else leave it empty.    
+   GITCHEK=
+   # Supported COMPRESS types are: tar.gz, tar.xz, bz2, rar, gz, tar, tbz2, tgz, zip, Z, 7z
+   #OR repos: cvn, cvs, git, lftp
    COMPRESS="git"
    SRCNAM=hyprutils
    PRGNAM=hyprutils
    VERSION=0.2.1
-   GITCHEK=  #if need git checkout example: GITCHEK=1029wk4952kk3xne7654
-
 
    BUILD=${BUILD:-1}
    TAG=${TAG:-_rtz}
@@ -45,98 +56,15 @@ Packager="Anagnostakis Ioannis (rizitis@gmail.com) GR"
    PKG=$CWD/package-$PRGNAM
    TMP=$CWD/work
    OUTPUT=$CWD/binary-$PRGNAM-$VERSION
+
+
    
-   DATE="$(date)"
-   NUMJOBS=${NUMJOBS:-"-j$(getconf _NPROCESSORS_ONLN)"}
-   DOCS="ABOUT* AUTHORS BUGS ChangeLog* COPYING CREDITS FAQ GPL* HACKING \
-      LICENSE MAINTAINERS NEWS README* TODO"
-   
-   if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) ARCH=i586 ;;
-    arm*) ARCH=arm ;;
-       *) ARCH=$( uname -m ) ;;
-  esac
-fi
+# START EDIT FUNCTIONS AS FOR YOUR NEEDS    
 
-if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
-  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
-  exit 0
-fi 
+   patch_build() { 
+true
+}
 
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
-  LIBDIRSUFFIX="64"
-elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
-  LIBDIRSUFFIX="64"
-else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
-fi
-
-
-
-  set -e
-
-   prepare_build(){
-	rm -rf "$PKG" "$OUTPUT" "$COMPRESS" "$CWD"/error-"$PRGNAM".log "$SRCNAM"
-	mkdir -p "$TMP" "$PKG" "$OUTPUT"
-	rm -rf "$TMP"/$PRGNAM-$VERSION
-	   if [[ $COMPRESS != "git" ]]; then
-  wget -O $SRCNAM-$VERSION.$COMPRESS "$SRCURL"
-else
-  if [ -z "$GITCHEK" ]; then
-    git clone $SRCURL
-  else
-    git clone $SRCURL
-    cd $SRCNAM || cd $PRGNAM || exit
-    git checkout $GITCHEK
-  fi
-fi
-	
-	get_out () {
-		if [ -f $1 ] ; then
-			case $1 in
-				*.tar.bz2)   tar xvjf $1    ;;
-				*.tar.gz)    tar xvzf $1    ;;
-				*.tar.xz)    tar xvJf $1    ;;
-				*.bz2)       bunzip2 $1     ;;
-				*.rar)       rar x $1       ;;
-				*.gz)        gunzip $1      ;;
-				*.tar)       tar xvf $1     ;;
-				*.tbz2)      tar xvjf $1    ;;
-				*.tgz)       tar xvzf $1    ;;
-				*.zip)       unzip $1       ;;
-				*.Z)         uncompress $1  ;;
-				*.7z)        7z x $1        ;;
-				*)           echo "don't know how to extract '$1'..." ;;
-			esac
-		else
-			echo "'$1' is not a valid file!"
-		fi
-       }
-       cd "$TMP" || exit 
-if [[ $COMPRESS != "git" ]]; then
-   get_out "$CWD"/"$SRCNAM"-"$VERSION"."$COMPRESS" || exit
-   cd $SRCNAM-$VERSION || cd $PRGNAM-$VERSION ||exit
-  else
-  mv $CWD/$SRCNAM . || mv $CWD/$PRGNAM . || true
-   cd $SRCNAM || cd $PRGNAM ||exit
-fi
-   }
-
-   patch_build(){
-#	patch -p0 < smallpatch || exit
-#	zcat $CWD/bigpatch.diff.gz | patch -p1 || exit
-	true
-   }
 
    chrooting(){
    	chown -R root:root .
@@ -192,42 +120,74 @@ fi
    }
    
    cmake_build(){
-	mkdir -p build
+   cd $TMP || exit
+   wget https://cdn-fastly.obsproject.com/downloads/cef_binary_5060_linux_x86_64_v3.tar.xz
+   tar -xf cef_binary_5060_linux_x86_64_v3.tar.xz
+   cd cef_binary_5060_linux_x86_64 || exit
+   strip -v Release/*.so
+   cmake \
+      -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
+      -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
+      -DCMAKE_BUILD_TYPE=Release .
+
+    make libcef_dll_wrapper
+     
+   cd $TMP/$SRCNAM-$VERSION/plugins || exit
+   git clone https://github.com/obsproject/obs-browser
+   git clone https://github.com/obsproject/obs-websocket 
+
+   cd  $TMP/$SRCNAM-$VERSION || exit 
+   mkdir -p build
 	cd build
-	  cmake \
-	    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
-	    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
-	    -DCMAKE_INSTALL_PREFIX=/usr \
-	    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
-	    -DMAN_INSTALL_DIR=/usr/man \
-	    -DCMAKE_BUILD_TYPE=Release ..
+	cmake \
+    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS -Wno-error=stringop-overflow" \
+    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS -Wno-error=stringop-overflow" \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_INSTALL_PREFIX=/usr \
+    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
+    -DOS_POSIX=ON \
+    -DOBS_VERSION_OVERRIDE=${VERSION} \
+    -DCMAKE_SKIP_INSTALL_RPATH=ON \
+    -DUNIX_STRUCTURE=ON \
+    -DCEF_ROOT_DIR="$TMP/cef_binary_5060_linux_x86_64" \
+    -DCALM_DEPRECATION=ON \
+    -DENABLE_AJA=OFF \
+    -DENABLE_LIBFDK=ON \
+    -DENABLE_JACK=ON \
+    -DENABLE_WEBRTC=OFF \
+    -DENABLE_WEBSOCKET=OFF \
+    -DOpenGL_GL_PREFERENCE=GLVND \
+    -DCALM_DEPRECATION=ON \
+    -DENABLE_VST=ON \
+    -DENABLE_NATIVE_NVENC=OFF \
+    -DCMAKE_BUILD_TYPE=Release ..
 	  make
 	  make install/strip DESTDIR=$PKG
 	cd ..
-}
+   }
 
-perl_build(){
-# Build method #1 (preferred)
-perl Makefile.PL \
+   perl_build(){
+        # Build method #1 (preferred)
+        perl Makefile.PL \
   PREFIX=/usr \
   INSTALLDIRS=vendor \
   INSTALLVENDORMAN1DIR=/usr/man/man1 \
   INSTALLVENDORMAN3DIR=/usr/man/man3
-make
-make test
-make install DESTDIR=$PKG
+        make
+        make test
+        make install DESTDIR=$PKG
 
 # Build method #2
 # requires perl-Module-Build or perl-Module-Build-Tiny
-perl Build.PL \
-  --installdirs vendor \
-  --config installvendorman1dir=/usr/man/man1 \
-  --config installvendorman3dir=/usr/man/man3
-./Build
-./Build test
-./Build install \
-  --destdir $PKG
-}
+        perl Build.PL \ 
+          --installdirs vendor \
+          --config installvendorman1dir=/usr/man/man1 \
+          --config installvendorman3dir=/usr/man/man3
+        ./Build
+        ./Build test
+        ./Build install \
+          --destdir $PKG
+   }
 
    haskel_build(){
 	CFLAGS="$SLKCFLAGS" \
@@ -252,6 +212,44 @@ perl Build.PL \
 	  mv $SRCNAM-$VERSION.conf "$PKG"/"$PKGCONFD"/"$PKGID".conf
    }
    
+   cargo_build() {
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
+
+/usr/bin/cargo build --release 
+
+        install -Dm755 "target/release/$PRGNAM" "$PKG/usr/bin/$PRGNAM"
+        install -Dm644 "assets/io.github.dimtpap.coppwr.desktop" "$PKG/usr/share/applications/io.github.dimtpap.coppwr.desktop"
+	install -Dm644 "assets/io.github.dimtpap.coppwr.metainfo.xml" "$PKG/usr/share/metainfo/io.github.dimtpap.coppwr.metainfo.xml"
+	install -Dm644 "assets/icon/scalable.svg" "$PKG/usr/share/icons/hicolor/scalable/apps/io.github.dimtpap.coppwr.svg"
+	install -Dm644 "assets/icon/512.png" "$PKG/usr/share/icons/hicolor/512x512/apps/io.github.dimtpap.coppwr.png"
+	install -Dm644 "assets/icon/256.png" "$PKG/usr/share/icons/hicolor/256x256/apps/io.github.dimtpap.coppwr.png"
+	install -Dm644 "assets/icon/128.png" "$PKG/usr/share/icons/hicolor/128x128/apps/io.github.dimtpap.coppwr.png"
+	install -Dm644 "assets/icon/64.png" "$PKG/usr/share/icons/hicolor/64x64/apps/io.github.dimtpap.coppwr.png"
+	install -Dm644 "assets/icon/48.png" "$PKG/usr/share/icons/hicolor/48x48/apps/io.github.dimtpap.coppwr.png"
+	install -Dm644 "assets/icon/32.png" "$PKG/usr/share/icons/hicolor/32x32/apps/io.github.dimtpap.coppwr.png"
+
+   }
+
+# golang_build dont need root access in Slackware if your setup is as SlackBuilds.org suggest for go.
+# examples for golang_build...
+   golang_build(){
+	  export CGO_CPPFLAGS="${CPPFLAGS}"
+	  export CGO_CFLAGS="${CFLAGS}"
+	  export CGO_CXXFLAGS="${CXXFLAGS}"
+	  export CGO_LDFLAGS="${LDFLAGS}"
+	  export GOFLAGS="???"
+	  CGO_ENABLED=0 \
+	  GOOS=linux \
+	  GOARCH=amd64 \
+	  go build \
+	  -ldflags='-w -s -extldflags "-static"' \
+	  ????
+
+  mkdir -p "$PKG"/usr/bin/
+  install -Dm755 "$PRGNAM"-"$VERSION"/? "$PKG"/usr/bin/"$PRGNAM"
+  }
+   
    custom_build(){
     cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
 	cmake --build ./build --config Release --target all
@@ -265,62 +263,66 @@ DESTDIR=$PKG cmake --install build
 	  find "$PKG"/usr/doc/$PRGNAM-$VERSION -type f -exec chmod 644 {} \;
 
 	  mkdir -p "$PKG"/install
-if [ -f "$CWD"/doinst.sh ]; then
+        if [ -f "$CWD"/doinst.sh ]; then
 	  cat "$CWD"/doinst.sh >> "$PKG"/install/doinst.sh
 	elif [ -f "$CWD"/doinst.sh.gz ]; then
 	  zcat "$CWD"/doinst.sh.gz >> "$PKG"/install/doinst.sh
 	else
-	  cat <<MKINS >> "$PKG"/install/doinst.sh
-config() {
-  for infile in \$1; do
-    NEW="\$infile"
-    OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
-    if [ ! -r \$OLD ]; then
-      mv \$NEW \$OLD
-    elif [ "\$(cat \$OLD | md5sum)" = "\$(cat \$NEW | md5sum)" ]; then
-      rm \$NEW
-    fi
-  done
-}
 
-preserve_perms() {
-  NEW="\$1"
-  OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
-  if [ -e \$OLD ]; then
-    cp -a \$OLD \${NEW}.incoming
-    cat \$NEW > \${NEW}.incoming
-    mv \${NEW}.incoming \$NEW
-  fi
-  config \$NEW
-}
+  cat <<MKINS >> "$PKG"/install/doinst.sh
+        config() {
+          for infile in \$1; do
+            NEW="\$infile"
+            OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
+            if [ ! -r \$OLD ]; then
+              mv \$NEW \$OLD
+            elif [ "\$(cat \$OLD | md5sum)" = "\$(cat \$NEW | md5sum)" ]; then
+            rm \$NEW
+            fi
+            done
+           }
 
-
-preserve_perms etc/rc.d/rc.INIT.new
-config etc/configfile.new
+        preserve_perms() {
+          NEW="\$1"
+          OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
+          if [ -e \$OLD ]; then
+            cp -a \$OLD \${NEW}.incoming
+            cat \$NEW > \${NEW}.incoming
+            mv \${NEW}.incoming \$NEW
+          fi
+          config \$NEW
+          }
 
 
-if [ -x usr/bin/update-desktop-database ]; then
-  chroot . /usr/bin/update-desktop-database usr/share/applications > /dev/null 2>&1
-fi
+#        preserve_perms etc/rc.d/rc.INIT.new
+#        config etc/configfile.new
 
-if [ -d usr/share/icons/hicolor ]; then
-  if [ -x /usr/bin/gtk-update-icon-cache ]; then
-    chroot . /usr/bin/gtk-update-icon-cache -f -t usr/share/icons/hicolor 1> /dev/null 2> /dev/null
-  fi
-fi
+        if [ -x /usr/bin/fc-cache ]; then
+          /usr/bin/fc-cache -fv /usr/share/fonts/
+        fi
 
-if [ -e usr/share/glib-2.0/schemas ]; then
-  if [ -x /usr/bin/glib-compile-schemas ]; then
-    /usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
-  fi
-fi 
+        if [ -x usr/bin/update-desktop-database ]; then
+          chroot . /usr/bin/update-desktop-database usr/share/applications > /dev/null 2>&1
+        fi
 
-if [ -x usr/bin/update-mime-database ]; then
-  chroot . /usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
-fi
+        if [ -d usr/share/icons/hicolor ]; then
+          if [ -x /usr/bin/gtk-update-icon-cache ]; then
+            chroot . /usr/bin/gtk-update-icon-cache -f -t usr/share/icons/hicolor 1> /dev/null 2> /dev/null
+          fi
+        fi
+
+        if [ -e usr/share/glib-2.0/schemas ]; then
+          if [ -x /usr/bin/glib-compile-schemas ]; then
+            /usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
+          fi
+        fi 
+
+        if [ -x usr/bin/update-mime-database ]; then
+          chroot . /usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
+        fi
 
 MKINS
-fi
+   fi
 	if [ -f "$CWD"/slack-desc ]; then
 	  cat "$CWD"/slack-desc > "$PKG"/install/slack-desc
 	 elif [ -x "$mkdesc" ]; then
@@ -360,7 +362,9 @@ fi
 
    }
    
+   
    package_build() {
+   cd $PKG || exit 66
 	  rm -f "$PKG"/{,usr/}lib${LIBDIRSUFFIX}/*.la
 	  find "$PKG" | xargs file | grep -e "executable" -e "shared object" | grep ELF \
 	  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
@@ -385,29 +389,208 @@ fi
    
    clean_src(){
 	cd $CWD || exit
-	rm -r package-"$PRGNAM" work *.$COMPRESS 
+	rm -r package-"$PRGNAM" work *.$COMPRESS || true
    }
 
    pkg_install(){
 	upgradepkg --install-new --reinstall "$OUTPUT"/$PRGNAM-$VERSION-"$ARCH"-"$BUILD""$TAG"."$PKGTYPE"
    }
+   
+   
+   
+  sig_package(){
+#  Add you id_rsa, example:
+    prikey_path="/root/id_rsa"
+         openssl dgst -sha256 -sign $prikey_path  -out "$OUTPUT"/$PRGNAM-$VERSION-"$ARCH"-"$BUILD""$TAG"."$PKGTYPE".sig "$OUTPUT"/$PRGNAM-$VERSION-"$ARCH"-"$BUILD""$TAG"."$PKGTYPE" 
+   } 
+   
+   
+   # END OF EDIT # Just uncomment needed functions at the end of script!
+   
+   
+   if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) ARCH=i586 ;;
+    arm*) ARCH=arm ;;
+       *) ARCH=$( uname -m ) ;;
+  esac
+fi
 
-# default most of the times
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
+  exit 0
+fi 
+
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
+  LIBDIRSUFFIX="64"
+elif [ "$ARCH" = "aarch64" ]; then
+  SLKCFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
+  LIBDIRSUFFIX="64"
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
+fi
+     
+   DATE="$(date)"
+   NUMJOBS=${NUMJOBS:-"-j$(getconf _NPROCESSORS_ONLN)"}
+DOCS=\
+"ABOUT \
+ABOUT-NLS \
+ANNOUNCE \
+AUTHORS \
+*BUGS* \
+ChangeLog \
+Changelog \
+CHANGELOG \
+Changes \
+CHANGES \
+COPYING \
+COPYRIGHT \
+CREDITS \
+CONFIGURATION* \
+CONTRIBUTING* \
+CONTRIBUTORS \
+doc \
+docs* \
+Doc \
+Docs* \
+*FAQ* \
+FEATURES \
+FILES \
+GPL* \
+HACKING \
+History \
+HISTORY \
+index.ht* \
+*INDEX* \
+INSTALL* \
+License* \
+LICENSE* \
+LSM \
+MANIFEST \
+NEWS \
+*README* \
+*Readme* \
+*RELEASE* \
+RELNOTES \
+Roadmap \
+ROADMAP \
+SITES \
+THANKS \
+TIPS \
+TODO \
+VERSION"
+
+download_src(){
+  if [[ $COMPRESS = "git" ]]; then
+    GIT="$(which git)"
+    $GIT clone "$SRCURL"
+    if [ -n "$GITCHEK" ]; then
+      cd "$SRCNAM" || cd "$PRGNAM" || exit
+      $GIT checkout "$GITCHEK"
+    fi
+  elif [[ $COMPRESS = "svn" ]]; then
+    SVN="$(which svn)"
+    $SVN co "$SRCURL"
+  elif [[ $COMPRESS = "cvs" ]]; then
+    CVS="$(which cvs)"
+    $CVS -z3 -f "$SRCURL"
+  elif [[ $COMPRESS = "lftp" ]]; then
+    LFTP="$(which lftp)"
+    $LFTP -c mirror "$SRCURL"
+  else
+    wget -O "$SRCNAM"-"$VERSION"."$COMPRESS" "$SRCURL"
+  fi
+}
+  set -e
+
+   prepare_build(){
+	rm -rf "$PKG" "$OUTPUT" "$COMPRESS" "$CWD"/error-"$PRGNAM".log
+	mkdir -p "$TMP" "$PKG" "$OUTPUT"
+	rm -rf "$TMP"/$PRGNAM-$VERSION
+	
+	get_out() {
+    if [ -f "$1" ] ; then
+        case "$1" in
+            *.tar.bz2)  tar xvjf "$1" ;;
+            *.tar.gz)   tar xvzf "$1" ;;
+            *.tar.xz)   tar xvJf "$1" ;;
+            *.bz2)      bunzip2 "$1"  ;;
+            *.rar)      rar x "$1"    ;;
+            *.gz)       gunzip "$1"   ;;
+            *.tar)      tar xvf "$1"  ;;
+            *.tbz2)     tar xvjf "$1" ;;
+            *.tgz)      tar xvzf "$1" ;;
+            *.zip)      unzip "$1"    ;;
+            *.Z)        uncompress "$1" ;;
+            *.7z)       7z x "$1"     ;;
+            *)          echo "Error: Don't know how to extract '$1'." ;;
+        esac
+    elif [ -n "$SRCNAM" ] && [ -n "$VERSION" ] && [ -f "$SRCNAM-$VERSION" ]; then
+        case "$SRCNAM-$VERSION" in
+            *.tar.bz2)  tar xvjf "$SRCNAM-$VERSION" ;;
+            *.tar.gz)   tar xvzf "$SRCNAM-$VERSION" ;;
+            *.tar.xz)   tar xvJf "$SRCNAM-$VERSION" ;;
+            *.bz2)      bunzip2 "$SRCNAM-$VERSION"  ;;
+            *.rar)      rar x "$SRCNAM-$VERSION"    ;;
+            *.gz)       gunzip "$SRCNAM-$VERSION"   ;;
+            *.tar)      tar xvf "$SRCNAM-$VERSION"  ;;
+            *.tbz2)     tar xvjf "$SRCNAM-$VERSION" ;;
+            *.tgz)      tar xvzf "$SRCNAM-$VERSION" ;;
+            *.zip)      unzip "$SRCNAM-$VERSION"    ;;
+            *.Z)        uncompress "$SRCNAM-$VERSION" ;;
+            *.7z)       7z x "$SRCNAM-$VERSION"     ;;
+            *)          echo "Error: Don't know how to extract '$SRCNAM-$VERSION'." ;;
+        esac
+    else
+        echo "Error: '$1' is not a valid file!"
+    fi
+}
+
+   	
+        cd "$TMP" || exit 
+        if [[ $COMPRESS != "git" && $COMPRESS != "svn" && $COMPRESS != "cvs" && $COMPRESS != "lftp" ]]; then
+          get_out "$CWD"/"$SRCNAM"-"$VERSION"."$COMPRESS" || exit
+           cd $SRCNAM-$VERSION || cd $PRGNAM-$VERSION ||exit
+          else
+          mv "$CWD"/"$SRCNAM" "$TMP"
+           cd $SRCNAM || cd $PRGNAM ||exit
+        fi
+   }
+   
+
+# default most of times #
+
+download_src
 prepare_build
+patch_build
+# uncomment what you need:
 chrooting
-
 #auto_build
 #meson_build
 #python_build
 #cmake_build
 #perl_build
 #haskel_build
-
+#cargo_build
+#golang_build
 custom_build
 
+# default most of times #
 after_build
 package_build
-
-#pkg_install
 clean_src
+#pkg_install
+sig_package
 
+# Calculate and display build time
+end_time=$(date +%s)
+elapsed_time=$((end_time - start_time))
+echo "Build process completed in $((elapsed_time / 60)) minutes and $((elapsed_time % 60)) seconds."
