add dinit TESTING SCRIPT

diff --git a/TEMPLATE.SlackBuild b/TEMPLATE.SlackBuild
--- a/TEMPLATE.SlackBuild
+++ b/TEMPLATE.SlackBuild
@@ -561,54 +561,150 @@ fi
 }
 # here ^^ end prepare_build function ;) #
 
-# Base System vars, here is the top of Script LOL.
 # Detect the architecture if not already set
 if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) ARCH=i586 ;;
-    arm*) ARCH=arm ;;
-       *) ARCH=$( uname -m ) ;;
+  case "$(uname -m)" in
+    i386) ARCH=i586 ;;          # 32-bit Intel architecture
+    i686) ARCH=i686 ;;          # 32-bit Intel architecture (optimized)
+    x86_64) ARCH=x86_64 ;;      # 64-bit Intel architecture
+    armv7* | armhf) ARCH=armv7 ;;  # ARMv7 (32-bit, hardware float)
+    armv6* | armv5*) ARCH=armv6 ;;  # ARMv6 (32-bit)
+    aarch64 | arm64) ARCH=aarch64 ;;  # ARMv8 (64-bit)
+    ppc | ppc64) ARCH=ppc ;;     # PowerPC (32-bit or 64-bit)
+    s390x) ARCH=s390x ;;        # IBM System Z (64-bit)
+    mips*) ARCH=mips ;;         # MIPS (various variants)
+    riscv64) ARCH=riscv64 ;;    # RISC-V 64-bit
+    sparc64) ARCH=sparc64 ;;     # SPARC (64-bit)
+    *) 
+      echo "Error: Unsupported architecture '$(uname -m)'. Exiting."
+      exit 1 
+      ;;
   esac
 fi
 
+echo "Detected architecture: $ARCH"
+
 # Output package name if required
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
-  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
+  echo "${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE}"
   exit 0
 fi
 
-# Set compiler flags based on architecture
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-  QMAKE_CFLAGS="-O2 -m32 -march=i586 -mtune=i686"
-  QMAKE_CXXFLAGS="-O2 -m32 -march=i586 -mtune=i686"
-  QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-  QMAKE_CFLAGS="-O2 -m32 -march=i686 -mtune=i686"
-  QMAKE_CXXFLAGS="-O2 -m32 -march=i686 -mtune=i686"
-  QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
-  LIBDIRSUFFIX="64"
-  QMAKE_CFLAGS="-O2 -m64 -march=x86-64 -mtune=generic -fPIC"
-  QMAKE_CXXFLAGS="-O2 -m64 -march=x86-64 -mtune=generic -fPIC"
-  QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
-elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
-  LIBDIRSUFFIX="64"
-  QMAKE_CFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
-  QMAKE_CXXFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
-  QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
-else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
-  QMAKE_CFLAGS="-O2"
-  QMAKE_CXXFLAGS="-O2"
-  QMAKE_LFLAGS="-L/usr/lib"
+# Check if ARCH is set (redundant here, but kept for safety)
+if [ -z "$ARCH" ]; then
+  echo "Error: ARCH variable is not set. Please set it to the target architecture."
+  exit 1
 fi
+
+# Set compiler flags based on architecture for musl/GCC
+case "$ARCH" in
+  "i586")
+    SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+    LIBDIRSUFFIX=""
+    QMAKE_CFLAGS="-O2 -m32 -march=i586 -mtune=i686"
+    QMAKE_CXXFLAGS="-O2 -m32 -march=i586 -mtune=i686"
+    QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
+    ;;
+    
+  "i686")
+    SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+    LIBDIRSUFFIX=""
+    QMAKE_CFLAGS="-O2 -m32 -march=i686 -mtune=i686"
+    QMAKE_CXXFLAGS="-O2 -m32 -march=i686 -mtune=i686"
+    QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
+    ;;
+    
+  "x86_64")
+    SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
+    LIBDIRSUFFIX="64"
+    QMAKE_CFLAGS="-O2 -m64 -march=x86-64 -mtune=generic -fPIC"
+    QMAKE_CXXFLAGS="-O2 -m64 -march=x86-64 -mtune=generic -fPIC"
+    QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
+    ;;
+    
+  "armv7")
+    SLKCFLAGS="-O2 -march=armv7-a -mtune=generic -fPIC"
+    LIBDIRSUFFIX=""
+    QMAKE_CFLAGS="-O2 -m32 -march=armv7-a -mtune=generic -fPIC"
+    QMAKE_CXXFLAGS="-O2 -m32 -march=armv7-a -mtune=generic -fPIC"
+    QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
+    ;;
+    
+  "armv6")
+    SLKCFLAGS="-O2 -march=armv6 -mtune=generic -fPIC"
+    LIBDIRSUFFIX=""
+    QMAKE_CFLAGS="-O2 -m32 -march=armv6 -mtune=generic -fPIC"
+    QMAKE_CXXFLAGS="-O2 -m32 -march=armv6 -mtune=generic -fPIC"
+    QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
+    ;;
+    
+  "aarch64")
+    SLKCFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
+    LIBDIRSUFFIX="64"
+    QMAKE_CFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
+    QMAKE_CXXFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
+    QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
+    ;;
+    
+  "ppc")
+    SLKCFLAGS="-O2 -mppc"
+    LIBDIRSUFFIX=""
+    QMAKE_CFLAGS="-O2 -m32 -mppc"
+    QMAKE_CXXFLAGS="-O2 -m32 -mppc"
+    QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
+    ;;
+    
+  "ppc64")
+    SLKCFLAGS="-O2 -mppc64"
+    LIBDIRSUFFIX="64"
+    QMAKE_CFLAGS="-O2 -m64 -mppc64"
+    QMAKE_CXXFLAGS="-O2 -m64 -mppc64"
+    QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
+    ;;
+    
+  "s390x")
+    SLKCFLAGS="-O2 -march=s390x"
+    LIBDIRSUFFIX="64"
+    QMAKE_CFLAGS="-O2 -m64 -march=s390x"
+    QMAKE_CXXFLAGS="-O2 -m64 -march=s390x"
+    QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
+    ;;
+    
+  "mips")
+    SLKCFLAGS="-O2 -march=mips32"
+    LIBDIRSUFFIX=""
+    QMAKE_CFLAGS="-O2 -m32 -march=mips32"
+    QMAKE_CXXFLAGS="-O2 -m32 -march=mips32"
+    QMAKE_LFLAGS="-L/usr/lib -L/usr/local/lib"
+    ;;
+    
+  "riscv64")
+    SLKCFLAGS="-O2 -march=rv64imac -mabi=lp64"
+    LIBDIRSUFFIX="64"
+    QMAKE_CFLAGS="-O2 -m64 -march=rv64imac -mabi=lp64"
+    QMAKE_CXXFLAGS="-O2 -m64 -march=rv64imac -mabi=lp64"
+    QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
+    ;;
+
+  "sparc64")
+    SLKCFLAGS="-O2 -m64"
+    LIBDIRSUFFIX="64"
+    QMAKE_CFLAGS="-O2 -m64"
+    QMAKE_CXXFLAGS="-O2 -m64"
+    QMAKE_LFLAGS="-L/usr/lib64 -L/usr/local/lib64"
+    ;;
+
+  *)
+    echo "Warning: Unsupported architecture '$ARCH'. Using generic flags."
+    SLKCFLAGS="-O2"
+    LIBDIRSUFFIX=""
+    QMAKE_CFLAGS="-O2"
+    QMAKE_CXXFLAGS="-O2"
+    QMAKE_LFLAGS="-L/usr/lib"
+    ;;
+esac
+
+
 
 NUMJOBS=${NUMJOBS:-"-j$(getconf _NPROCESSORS_ONLN)"}
 
